"""Recompute saved-data summaries; no model loading or network access.

Run: python -m analysis.reproduce --output-dir build/reproduced
Expected files are archived published aggregates, not generated by this module.
"""
from pathlib import Path
import argparse
import hashlib
import json

import numpy as np
import pandas as pd
from scipy.stats import pearsonr, rankdata, spearmanr
from . import snapshot
from .snapshot import CHECKPOINT, METRICS, STATE, THRESHOLD_COLUMNS, filename, metadata, validate_checkpoints

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"


def read(name):
    return pd.read_csv(DATA / name, float_precision="round_trip")


def compare(actual, expected_name, keys, checks):
    expected = read("expected/" + expected_name)
    actual = actual.sort_values(keys).reset_index(drop=True)
    expected = expected.sort_values(keys).reset_index(drop=True)
    if len(actual) != len(expected):
        raise ValueError(f"Row count differs: {expected_name}")
    for column in expected.columns:
        if pd.api.types.is_numeric_dtype(expected[column]):
            np.testing.assert_allclose(actual[column], expected[column],
                                       rtol=1e-9, atol=1e-10, equal_nan=True,
                                       err_msg=f"{expected_name}:{column}")
        else:
            pd.testing.assert_series_equal(actual[column], expected[column], check_names=False)
    checks.append({"reference": "data/expected/" + expected_name,
                   "rows": len(expected), "compared_columns": list(expected.columns), "passed": True})


def rq1(output, checks):
    frame = read(filename("rq1"))
    assert len(frame) == 40000 and not frame.duplicated(STATE + ["edit_index"]).any()
    rows = []
    for key, group in frame.groupby(STATE, sort=True):
        assert len(group) == 1000
        x = group.returned_target_ratio.to_numpy()
        y = group.actual_post_pre_ratio.to_numpy()
        fit = np.polyfit(x, y, 1)
        residual = y - np.polyval(fit, x)
        rows.append(dict(zip(STATE, key), n=len(group), regression_intercept=fit[1],
            regression_slope=fit[0], regression_r2=1 - np.sum(residual**2) / np.sum((y-y.mean())**2),
            target_actual_spearman=spearmanr(x,y)[0], target_ratio_median=np.median(x),
            actual_ratio_median=np.median(y), actual_lt_target_count=np.sum(y<x),
            target_nonexpands_count=np.sum(x<=1+1e-6), actual_nonexpands_count=np.sum(y<=1+1e-6),
            pi_z=np.mean(x<=1+1e-6), pi_post=np.mean(y<=1+1e-6)))
    result = pd.DataFrame(rows)
    compare(result, "rq1_condition_summary_40.csv", STATE, checks)
    result.to_csv(output / "rq1_condition_summary_40.csv", index=False)


def partial_spearman(x, y, control):
    rx, ry, rz = [rankdata(np.asarray(v, float)) for v in [x,y,control]]
    design = np.column_stack([np.ones(len(rx)), rz])
    ex = rx - design @ np.linalg.lstsq(design, rx, rcond=None)[0]
    ey = ry - design @ np.linalg.lstsq(design, ry, rcond=None)[0]
    return pearsonr(ex, ey)[0]


def rq2(output, checks):
    frame = read(filename("rq2"))
    validate_checkpoints(frame)
    columns = THRESHOLD_COLUMNS
    assert np.isfinite(frame[columns]).all().all()
    retained = frame[columns].le(3).all(axis=1)
    mask = frame[CHECKPOINT].copy()
    mask["excluded_above3"] = ~retained
    mask["kept_after_threshold3"] = retained
    compare(mask, filename("rq2_mask"), CHECKPOINT, checks)
    mask.to_csv(output / "rq2_threshold_mask.csv", index=False)
    kept = frame[retained].copy()
    expected_count = metadata().get("rq2_retained_checkpoints")
    if expected_count is not None:
        assert len(kept) == expected_count
    rows = []
    for dataset, group in kept.groupby("dataset"):
        for context in ["locality", "rewrite"]:
            for metric in METRICS:
                x, y = group[context + "_" + metric], group.locality_percent
                rows.append(dict(dataset=dataset, geometry_context=context, metric=metric,
                    n=len(group), n_trajectories=len(group[STATE].drop_duplicates()),
                    spearman=spearmanr(x,y)[0], pearson=pearsonr(x,y)[0],
                    partial_spearman_given_D=partial_spearman(x,y,group[context+"_mean_abs_norm_deviation"])
                    if metric=="mean_q" else np.nan))
    result = pd.DataFrame(rows)
    compare(result, "rq2_correlations.csv", ["dataset","geometry_context","metric"], checks)
    result.to_csv(output / "rq2_correlations.csv", index=False)
    kept.to_csv(output / "rq2_retained_checkpoints.csv", index=False)
    if all(context + "_mean_d" in kept for context in ["locality", "rewrite"]):
        drift_rows = []
        for dataset, group in kept.groupby("dataset"):
            for context in ["locality", "rewrite"]:
                q, d, deviation = [group[context + "_" + name]
                                   for name in ["mean_q", "mean_d", "mean_abs_norm_deviation"]]
                assert np.isfinite(d).all()
                drift_rows.append(dict(dataset=dataset, geometry_context=context,
                    n_checkpoints=len(group), rho_q_LOC=spearmanr(q, group.locality_percent)[0],
                    rho_d_LOC=spearmanr(d, group.locality_percent)[0],
                    rho_DH_LOC=spearmanr(deviation, group.locality_percent)[0], rho_q_d=spearmanr(q,d)[0]))
        drift = pd.DataFrame(drift_rows)
        if "rq2_drift" in metadata()["files"]:
            compare(drift, filename("rq2_drift"), ["dataset", "geometry_context"], checks)
        drift.to_csv(output / "rq2_drift_correlations.csv", index=False)
    energy_rows = []
    for context in ["locality", "rewrite"]:
        moment_columns = [context + "_" + name for name in
                          ["mean_p", "mean_p_squared", "mean_q_squared", "mean_kappa_squared"]]
        if not set(moment_columns).issubset(kept.columns):
            continue
        if metadata().get("complete_second_moments"):
            assert np.isfinite(kept[moment_columns]).all().all()
        part = kept.dropna(subset=moment_columns)
        if part.empty:
            continue
        p, p2, q2, kappa2 = [part[name].to_numpy() for name in moment_columns]
        # Second moments are case-wise means, never squares of checkpoint means.
        np.testing.assert_allclose(2*p+p2+q2, kappa2-1, atol=1e-7, rtol=1e-7)
        energy = part[CHECKPOINT].copy()
        energy["geometry_context"] = context
        energy["P"] = 2*p+p2
        energy["Q"] = q2
        energy["mean_squared_norm_increase"] = kappa2-1
        energy["compensation_ratio"] = -(2*p+p2)/q2
        energy["orthogonal_displacement_energy_fraction"] = q2/(p2+q2)
        energy_rows.append(energy)
    if energy_rows:
        pd.concat(energy_rows, ignore_index=True).to_csv(output / "rq2_checkpoint_energy.csv", index=False)
    if "locality_endpoints" in metadata()["files"]:
        endpoint_rows = []
        for context, role in [("rewrite", "figure4"), ("locality", "locality_endpoints")]:
            endpoints = read(filename(role))
            assert endpoints.order_id.eq("canonical").all()
            p = 2*endpoints.mean_p+endpoints.mean_p_squared
            q = endpoints.mean_q_squared
            increase = endpoints.mean_kappa_squared-1
            np.testing.assert_allclose(p+q, increase, atol=1e-7, rtol=1e-7)
            c = -p/q
            endpoint_rows.append(dict(context=context, n_endpoints=len(endpoints),
                median_c=c.median(), c_q25=c.quantile(.25), c_q75=c.quantile(.75),
                Q_above1=int(q.gt(1).sum()), P_above0=int(p.gt(0).sum()),
                mean_squared_norm_grows=int(increase.gt(0).sum())))
        endpoint_summary = pd.DataFrame(endpoint_rows)
        compare(endpoint_summary, filename("endpoint_summary"), ["context"], checks)
        endpoint_summary.to_csv(output / "endpoint_norm_decomposition_summary.csv", index=False)
    return dict(available=len(frame), retained=len(kept), excluded=len(frame)-len(kept),
                trajectories=len(frame[STATE].drop_duplicates()),
                dataset_retained_counts=kept.groupby("dataset").size().to_dict())


def rq3(output, checks):
    frame = read(filename("rq3_doses"))
    assert len(frame) == 200 and not frame.duplicated(CHECKPOINT+["dose_fraction"]).any()
    rows = []
    for dose, group in frame[frame.dose_fraction.gt(0)].groupby("dose_fraction"):
        assert len(group) == 40
        # Published joint-count classification uses unrounded saved per-state indicators.
        rows.append(dict(removed_fraction=dose, n_states=len(group),
            mean_delta_LOC=group.delta_LOC.mean(), mean_delta_EFF_TF=group.delta_EFF_TF.mean(),
            mean_delta_GEN_TF=group.delta_GEN_TF.mean(),
            LOC_up_no_edit_loss=int(group.LOC_up_no_edit_loss.sum()),
            LOC_up_both_losses_at_most_1pp=int(group.LOC_up_both_losses_at_most_1pp.sum())))
    result = pd.DataFrame(rows)
    compare(result, "rq3_orthogonal_dose_summary.csv", ["removed_fraction"], checks)
    result.to_csv(output / "rq3_orthogonal_dose_summary.csv", index=False)

    conditions = read(filename("rq3_same_norm"))
    conditions["endpoint"] = conditions.endpoint.str.upper()
    assert len(conditions) == 480 and conditions.scope.eq("B_common_all_families").all()
    index = CHECKPOINT+["dose_fraction"]
    operations = ["perp", "projection_match"]
    endpoints = ["LOC", "EFF", "GEN"]
    assert set(conditions.operation) == set(operations)
    assert set(conditions.endpoint) == set(endpoints)
    assert set(conditions.dose_fraction) == {.25, .5}
    assert not conditions.duplicated(index+["operation", "endpoint"]).any()
    assert conditions.groupby(index).size().eq(len(operations)*len(endpoints)).all()
    assert conditions.groupby(index).n_cases.nunique().eq(1).all()
    assert conditions.n_cases.ge(0).all()
    eligible = conditions[conditions.n_cases.gt(0)].copy()
    wide = eligible.pivot(index=index, columns=["operation","endpoint"], values="delta_pp")
    wide = wide.reindex(columns=pd.MultiIndex.from_product([operations, endpoints]))
    assert np.isfinite(wide).all().all()
    counts = eligible.groupby(index).n_cases
    assert counts.nunique().eq(1).all()
    differences = wide.index.to_frame(index=False)
    differences["n_cases"] = counts.first().reindex(wide.index).to_numpy()
    for endpoint, metric in [("LOC","LOC"),("EFF","EFF_TF"),("GEN","GEN_TF")]:
        differences["difference_"+metric+"_pp"] = (wide["projection_match",endpoint]-wide["perp",endpoint]).to_numpy()
    compare(differences, filename("rq3_differences"), index, checks)
    differences.to_csv(output / "rq3_same_norm_state_differences.csv", index=False)
    means = []
    dose_counts = {}
    for dose in [.25,.5]:
        state_values = wide[wide.index.get_level_values("dose_fraction") == dose].droplevel("dose_fraction")
        dose_counts[str(dose)] = dict(eligible_states=len(state_values),
            total_state_case_count=int(differences[differences.dose_fraction.eq(dose)].n_cases.sum()))
        for operation, source in [("orthogonal","perp"),("parallel","projection_match"),("parallel_minus_orthogonal",None)]:
            values = state_values[source] if source else state_values["projection_match"]-state_values["perp"]
            means.append(dict(scope="all_cohorts_equal_eligible_state", dose_fraction=dose,
                dose_percent=round(100*dose),operation=operation,n_states=len(values),
                total_state_case_count=int(differences[differences.dose_fraction.eq(dose)].n_cases.sum()),
                n_joint_condition=int(((values.LOC>1e-10)&(values.EFF>=-1e-10)&(values.GEN>=-1e-10)).sum()),
                mean_delta_LOC_pp=values.LOC.mean(),mean_delta_EFF_TF_pp=values.EFF.mean(),
                mean_delta_GEN_TF_pp=values.GEN.mean()))
    result = pd.DataFrame(means)
    compare(result,"rq3_same_norm_overall_means.csv",["dose_fraction","operation"],checks)
    result.to_csv(output / "rq3_same_norm_overall_means.csv", index=False)
    declared = metadata().get("rq3_same_norm_eligible_states_by_dose")
    if declared is not None:
        assert {dose: values["eligible_states"] for dose, values in dose_counts.items()} == declared
    return dict(orthogonal_states=len(frame[CHECKPOINT].drop_duplicates()),
                same_norm_eligible_state_dose_rows=len(wide), same_norm_by_dose=dose_counts)


def main():
    global DATA
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("build/reproduced"))
    parser.add_argument("--data-dir", type=Path, default=DATA)
    args = parser.parse_args()
    DATA = args.data_dir.resolve()
    snapshot.DATA = DATA
    output = args.output_dir.resolve()
    if output == DATA or DATA in output.parents:
        parser.error("Output must not overwrite the included source data directory")
    output.mkdir(parents=True, exist_ok=True)
    manifest = json.loads((DATA/"provenance/data_sources.json").read_text())
    for entry in manifest["files"]:
        path = DATA / entry["package_file"].removeprefix("data/")
        if hashlib.sha256(path.read_bytes()).hexdigest() != entry["package_sha256"]:
            raise ValueError("Saved input changed: " + entry["package_file"])
    checks=[]
    rq1(output,checks)
    rq3_counts = rq3(output,checks)
    latest = bool(metadata().get("manuscript_snapshot"))
    extended = {}
    if latest:
        from . import manuscript_statistics, manuscript_vectors_interventions
        inputs = DATA / metadata()["manuscript_data_directory"]
        extended["rq2"] = manuscript_statistics.run(inputs, output / "rq2")
        extended["rq1_rq3"] = manuscript_vectors_interventions.run(inputs, output / "rq1_rq3")
        rq2_counts = dict(available=metadata()["rq2_available_checkpoints"],
                          primary=metadata()["rq2_primary_checkpoints"],
                          retained=metadata()["rq2_retained_checkpoints"],
                          sensitivity=metadata()["rq2_sensitivity_checkpoints"],
                          trajectories=metadata()["rq2_available_trajectories"])
    else:
        rq2_counts = rq2(output,checks)
    performance=read(filename("performance"))
    assert len(performance)==40
    assert performance[["n_rewrite","n_rephrase","n_locality"]].eq(1000).all().all()
    assert not performance.duplicated(CHECKPOINT).any()
    if latest:
        score_columns = ["eff_tf_percent", "gen_tf_percent", "locality_percent"]
        assert performance.activation_intervention.eq("none").all()
        assert performance.target_span.str.contains("EOS/EOT").all()
        performance_name = "endpoint_tf_1000.csv"
    else:
        assert performance.available.all()
        score_columns = ["eff_percent", "gen_percent", "locality_percent"]
        performance_name = "performance_1k_40.csv"
    assert np.isfinite(performance[score_columns]).all().all()
    assert performance[score_columns].ge(0).all().all() and performance[score_columns].le(100).all().all()
    performance.to_csv(output/performance_name,index=False)
    report=dict(passed=True,source_snapshot_hashes_checked=len(manifest["files"]),
        reference_comparisons=checks,performance_conditions=40,model_inference_performed=False,
        rq2_counts=rq2_counts, rq3_counts=rq3_counts, snapshot=metadata(),
        manuscript_analysis=extended,
        endpoint_score_source="Saved endpoint scores; no token predictions or model inference regenerated",
        inferential_scope=("Saved measurements; whole-trajectory resampling for RQ2 and paired-case resampling for RQ3. Intervals do not represent independent editing runs."
                           if latest else "Descriptive summaries of saved measurements; no bootstrap intervals regenerated."),
        numpy_version=np.__version__,pandas_version=pd.__version__)
    (output/"validation.json").write_text(json.dumps(report,indent=2)+"\n")
    panel_summary = (f"RQ2 {rq2_counts['primary']} primary checkpoints, 337/306 sensitivity panels, "
                     if latest else f"RQ2 {rq2_counts['retained']}/{rq2_counts['available']} checkpoints, ")
    print(f"Validated {len(checks)} aggregate reference tables" +
          (" and the manuscript statistical analyses" if latest else "") + "; RQ1 40,000 edits, " +
          panel_summary +
          f"RQ3 {rq3_counts['orthogonal_states']} states; same-norm eligible states "
          + ", ".join(f"{float(dose)*100:g}%: {values['eligible_states']}"
                      for dose, values in rq3_counts['same_norm_by_dose'].items()) + ".")


if __name__ == "__main__":
    main()
