"""Recompute saved-data summaries; no model loading or network access.

Run: python -m analysis.reproduce --output-dir build/reproduced
Expected files are archived published aggregates, not generated by this module.
"""
from pathlib import Path
import argparse
import hashlib
import json

import numpy as np
import pandas as pd
from scipy.stats import pearsonr, rankdata, spearmanr

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
STATE = ["model", "dataset", "editor", "method", "order_id"]
CHECKPOINT = STATE + ["edit_count"]
METRICS = ["mean_q", "mean_kappa", "mean_abs_norm_deviation"]


def read(name):
    return pd.read_csv(DATA / name, float_precision="round_trip")


def compare(actual, expected_name, keys, checks):
    expected = read("expected/" + expected_name)
    actual = actual.sort_values(keys).reset_index(drop=True)
    expected = expected.sort_values(keys).reset_index(drop=True)
    if len(actual) != len(expected):
        raise ValueError(f"Row count differs: {expected_name}")
    for column in expected.columns:
        if pd.api.types.is_numeric_dtype(expected[column]):
            np.testing.assert_allclose(actual[column], expected[column],
                                       rtol=1e-9, atol=1e-10, equal_nan=True,
                                       err_msg=f"{expected_name}:{column}")
        else:
            pd.testing.assert_series_equal(actual[column], expected[column], check_names=False)
    checks.append({"reference": "data/expected/" + expected_name,
                   "rows": len(expected), "compared_columns": list(expected.columns), "passed": True})


def rq1(output, checks):
    frame = read("rq1_per_edit_40000.csv")
    assert len(frame) == 40000 and not frame.duplicated(STATE + ["edit_index"]).any()
    rows = []
    for key, group in frame.groupby(STATE, sort=True):
        assert len(group) == 1000
        x = group.returned_target_ratio.to_numpy()
        y = group.actual_post_pre_ratio.to_numpy()
        fit = np.polyfit(x, y, 1)
        residual = y - np.polyval(fit, x)
        rows.append(dict(zip(STATE, key), n=len(group), regression_intercept=fit[1],
            regression_slope=fit[0], regression_r2=1 - np.sum(residual**2) / np.sum((y-y.mean())**2),
            target_actual_spearman=spearmanr(x,y)[0], target_ratio_median=np.median(x),
            actual_ratio_median=np.median(y), actual_lt_target_count=np.sum(y<x),
            target_nonexpands_count=np.sum(x<=1+1e-6), actual_nonexpands_count=np.sum(y<=1+1e-6),
            pi_z=np.mean(x<=1+1e-6), pi_post=np.mean(y<=1+1e-6)))
    result = pd.DataFrame(rows)
    compare(result, "rq1_condition_summary_40.csv", STATE, checks)
    result.to_csv(output / "rq1_condition_summary_40.csv", index=False)


def partial_spearman(x, y, control):
    rx, ry, rz = [rankdata(np.asarray(v, float)) for v in [x,y,control]]
    design = np.column_stack([np.ones(len(rx)), rz])
    ex = rx - design @ np.linalg.lstsq(design, rx, rcond=None)[0]
    ey = ry - design @ np.linalg.lstsq(design, ry, rcond=None)[0]
    return pearsonr(ex, ey)[0]


def rq2(output, checks):
    frame = read("rq2_checkpoints_360.csv")
    assert len(frame) == 360 and not frame.duplicated(CHECKPOINT).any()
    columns = [context + "_" + metric for context in ["locality", "rewrite"] for metric in METRICS]
    assert np.isfinite(frame[columns]).all().all()
    retained = frame[columns].le(3).all(axis=1)
    mask = frame[CHECKPOINT].copy()
    mask["excluded_above3"] = ~retained
    mask["kept_after_threshold3"] = retained
    compare(mask, "rq2_threshold_mask_360.csv", CHECKPOINT, checks)
    mask.to_csv(output / "rq2_threshold_mask_360.csv", index=False)
    kept = frame[retained].copy()
    assert len(kept) == 337 and kept.groupby("dataset").size().to_dict() == {"CounterFact":151,"zsRE":186}
    rows = []
    for dataset, group in kept.groupby("dataset"):
        for context in ["locality", "rewrite"]:
            for metric in METRICS:
                x, y = group[context + "_" + metric], group.locality_percent
                rows.append(dict(dataset=dataset, geometry_context=context, metric=metric,
                    n=len(group), n_trajectories=len(group[STATE].drop_duplicates()),
                    spearman=spearmanr(x,y)[0], pearson=pearsonr(x,y)[0],
                    partial_spearman_given_D=partial_spearman(x,y,group[context+"_mean_abs_norm_deviation"])
                    if metric=="mean_q" else np.nan))
    result = pd.DataFrame(rows)
    compare(result, "rq2_correlations.csv", ["dataset","geometry_context","metric"], checks)
    result.to_csv(output / "rq2_correlations.csv", index=False)
    kept.to_csv(output / "rq2_retained_checkpoints_337.csv", index=False)


def rq3(output, checks):
    frame = read("rq3_orthogonal_states_doses_200.csv")
    assert len(frame) == 200 and not frame.duplicated(CHECKPOINT+["dose_fraction"]).any()
    rows = []
    for dose, group in frame[frame.dose_fraction.gt(0)].groupby("dose_fraction"):
        assert len(group) == 40
        # Published joint-count classification uses unrounded saved per-state indicators.
        rows.append(dict(removed_fraction=dose, n_states=len(group),
            mean_delta_LOC=group.delta_LOC.mean(), mean_delta_EFF_TF=group.delta_EFF_TF.mean(),
            mean_delta_GEN_TF=group.delta_GEN_TF.mean(),
            LOC_up_no_edit_loss=int(group.LOC_up_no_edit_loss.sum()),
            LOC_up_both_losses_at_most_1pp=int(group.LOC_up_both_losses_at_most_1pp.sum())))
    result = pd.DataFrame(rows)
    compare(result, "rq3_orthogonal_dose_summary.csv", ["removed_fraction"], checks)
    result.to_csv(output / "rq3_orthogonal_dose_summary.csv", index=False)

    conditions = read("rq3_same_norm_conditions_480.csv")
    conditions["endpoint"] = conditions.endpoint.str.upper()
    assert len(conditions) == 480 and conditions.scope.eq("B_common_all_families").all()
    eligible = conditions[conditions.n_cases.gt(0)].copy()
    assert len(eligible) == 408
    index = CHECKPOINT+["dose_fraction"]
    wide = eligible.pivot(index=index, columns=["operation","endpoint"], values="delta_pp")
    assert len(wide) == 68 and not wide.isna().any().any()
    counts = eligible.groupby(index).n_cases
    assert counts.nunique().eq(1).all()
    differences = wide.index.to_frame(index=False)
    differences["n_cases"] = counts.first().reindex(wide.index).to_numpy()
    for endpoint, metric in [("LOC","LOC"),("EFF","EFF_TF"),("GEN","GEN_TF")]:
        differences["difference_"+metric+"_pp"] = (wide["projection_match",endpoint]-wide["perp",endpoint]).to_numpy()
    compare(differences, "rq3_same_norm_state_differences_68.csv", index, checks)
    differences.to_csv(output / "rq3_same_norm_state_differences_68.csv", index=False)
    means = []
    for dose in [.25,.5]:
        state_values = wide.xs(dose,level="dose_fraction")
        assert len(state_values) == 34
        for operation, source in [("orthogonal","perp"),("parallel","projection_match"),("parallel_minus_orthogonal",None)]:
            values = state_values[source] if source else state_values["projection_match"]-state_values["perp"]
            means.append(dict(scope="all_cohorts_equal_eligible_state", dose_fraction=dose,
                dose_percent=round(100*dose),operation=operation,n_states=len(values),
                total_state_case_count=int(differences[differences.dose_fraction.eq(dose)].n_cases.sum()),
                n_joint_condition=int(((values.LOC>1e-10)&(values.EFF>=-1e-10)&(values.GEN>=-1e-10)).sum()),
                mean_delta_LOC_pp=values.LOC.mean(),mean_delta_EFF_TF_pp=values.EFF.mean(),
                mean_delta_GEN_TF_pp=values.GEN.mean()))
    result = pd.DataFrame(means)
    compare(result,"rq3_same_norm_overall_means.csv",["dose_fraction","operation"],checks)
    result.to_csv(output / "rq3_same_norm_overall_means.csv", index=False)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("build/reproduced"))
    args = parser.parse_args()
    output = args.output_dir.resolve()
    if output == DATA or DATA in output.parents:
        parser.error("Output must not overwrite the included source data directory")
    output.mkdir(parents=True, exist_ok=True)
    manifest = json.loads((DATA/"provenance/data_sources.json").read_text())
    for entry in manifest["files"]:
        path = ROOT/entry["package_file"]
        if hashlib.sha256(path.read_bytes()).hexdigest() != entry["package_sha256"]:
            raise ValueError("Saved input changed: " + entry["package_file"])
    checks=[]
    rq1(output,checks); rq2(output,checks); rq3(output,checks)
    performance=read("performance_1k_40.csv")
    assert len(performance)==40 and performance.available.all()
    assert performance[["n_rewrite","n_rephrase","n_locality"]].eq(1000).all().all()
    assert not performance.duplicated(CHECKPOINT).any()
    assert np.isfinite(performance[["eff_percent","gen_percent","locality_percent"]]).all().all()
    performance.to_csv(output/"performance_1k_40.csv",index=False)
    report=dict(passed=True,source_snapshot_hashes_checked=len(manifest["files"]),
        reference_comparisons=checks,performance_conditions=40,model_inference_performed=False,
        inferential_scope="Saved measurements; descriptive checkpoint/state aggregation. Checkpoints are not independent replicates.",
        numpy_version=np.__version__,pandas_version=pd.__version__)
    (output/"validation.json").write_text(json.dumps(report,indent=2)+"\n")
    print(f"Validated {len(checks)} reference tables; RQ1 40,000 edits, RQ2 337/360 checkpoints, RQ3 40 states and 34 eligible same-norm states.")


if __name__ == "__main__":
    main()
